import { config as loadDotEnv } from "dotenv"
import { resolve } from "node:path"
import { existsSync } from "node:fs"
import { writeFileSync } from "node:fs"
import {
  checkApiEnv,
  checkIngestionEnv,
  checkWebEnv,
  checkDbEnv,
  apiEnvDocs,
  ingestionEnvDocs,
  webEnvDocs,
  dbEnvDocs,
  type EnvReport,
} from "../src/index"

const REPO_ROOT = resolve(import.meta.dir, "..", "..", "..")

const APPS = {
  api: { name: "api", dir: "apps/api", check: checkApiEnv, docs: apiEnvDocs },
  ingestion: { name: "ingestion", dir: "apps/ingestion", check: checkIngestionEnv, docs: ingestionEnvDocs },
  web: { name: "web", dir: "apps/web", check: checkWebEnv, docs: webEnvDocs },
  db: { name: "db", dir: "packages/db", check: checkDbEnv, docs: dbEnvDocs },
} as const

type AppName = keyof typeof APPS

function envFilePath(app: AppName, explicit: string | undefined): string {
  if (explicit) {
    return resolve(process.cwd(), explicit)
  }
  return resolve(REPO_ROOT, APPS[app].dir, ".env")
}

function printReport(report: EnvReport<unknown>): void {
  const label = `${report.app.toUpperCase()} (${APPS[report.app as AppName]?.dir ?? report.app})`
  if (report.ok) {
    console.log(`✔ ${label} — env OK`)
  } else {
    console.log(`✖ ${label} — env INVALID`)
  }
  for (const issue of report.issues) {
    console.log(`    • ${issue.path}: ${issue.message}`)
  }
  for (const warning of report.warnings) {
    console.log(`    ⚠ ${warning.path}: ${warning.message}`)
  }
}

function runChecks(apps: AppName[], dotenvArg: string | undefined): boolean {
  let allOk = true
  for (const app of apps) {
    const file = envFilePath(app, dotenvArg)
    // When an explicit --dotenv file is given but doesn't exist, fall back to
    // validating the process environment (e.g. CI where env comes from the host).
    if (existsSync(file)) {
      loadDotEnv({ path: file, override: true, quiet: true })
    }

    const report = APPS[app].check()
    printReport(report as EnvReport<unknown>)
    if (!report.ok) allOk = false
  }
  return allOk
}

function renderExample(docs: typeof apiEnvDocs): string {
  const lines: string[] = ["# Generated by @hookscope/env — edit packages/env/src/docs.ts and re-run", "# `bun run check:env generate` to update this file."]

  let currentSection = ""
  for (const doc of docs) {
    if (doc.section !== currentSection) {
      currentSection = doc.section
      lines.push("", `# ─── ${currentSection} ─${"─".repeat(Math.max(0, 60 - currentSection.length - 8))}`)
    }
    const tag = doc.required ? " (required)" : ""
    lines.push(`# ${doc.description}${tag}`)
    lines.push(`${doc.key}=${doc.example ?? ""}`)
  }
  return lines.join("\n") + "\n"
}

function generateExamples(): void {
  const targets: { file: string; docs: typeof apiEnvDocs }[] = [
    { file: resolve(REPO_ROOT, "apps/api/.env.example"), docs: apiEnvDocs },
    { file: resolve(REPO_ROOT, "apps/ingestion/.env.example"), docs: ingestionEnvDocs },
    { file: resolve(REPO_ROOT, "apps/web/.env.example"), docs: webEnvDocs },
    { file: resolve(REPO_ROOT, "packages/db/.env.example"), docs: dbEnvDocs },
  ]
  for (const target of targets) {
    writeFileSync(target.file, renderExample(target.docs))
    console.log(`✔ wrote ${target.file.replace(`${REPO_ROOT}/`, "")}`)
  }
}

const usage = () => {
  console.log(`Usage:
  bun packages/env/scripts/check.ts <app|all> [--dotenv <file>]
  bun packages/env/scripts/check.ts generate

Apps: ${Object.keys(APPS).join(", ")}`)
  process.exit(1)
}

const arg = process.argv[2]
const dotenvArg = process.argv[3] === "--dotenv" ? process.argv[4] : undefined

if (arg === "generate") {
  generateExamples()
  process.exit(0)
}

if (arg === "all") {
  process.exit(runChecks(Object.keys(APPS) as AppName[], dotenvArg) ? 0 : 1)
}

if (arg && arg in APPS) {
  process.exit(runChecks([arg as AppName], dotenvArg) ? 0 : 1)
}

usage()
